[ECO-2186] Add market address to market registration events
econia-labs/aptos-indexer-processors pull request #53
Opened 2024-09-17 15:02 UTC by CRBl69

This PR adds a missed field (market address) in the market registration event. It is needed in the frontend AFAIK.

This is modified in place instead of making a new migration as this needs to be present from the start and needs a processor cold upgrade.

2024-09-17 20:24 UTC, xbtmatt reviewed
So I could've documented this better- but I left this out because you can deterministically derive the market address, given the contract address (and thus the registry address) + the emojis.

See here: https://github.com/econia-labs/emojicoin-dot-fun/blob/829bf56049d269ddf72d3733fabc1fb921b5a167/src/typescript/sdk/src/emojicoin_dot_fun/utils.ts#L24

I'm okay if we add this in as it's fine to have it, especially if the other tables are missing it, but we should add it to all tables that have the flattened `MarketMetadata` struct if we add it to this one

2024-09-17 20:57 UTC, alnoki requested changes

2024-09-17 20:57 UTC, alnoki commented on rust/processor/src/db/common/models/emojicoin_models/models/market_registration_event.rs
> +    pub market_address: String,
Per https://github.com/econia-labs/aptos-indexer-processors/pull/53#pullrequestreview-2310994448, while yes this field can technically be derived, I foresee that we will alleviate downstream indexing issues later if we simply include it here, in all applicable contexts

- [ ] Include in all other tables as needed for consistency and ease of indexing

2024-09-23 17:46 UTC, alnoki approved these changes

2024-09-26 08:31 UTC, merged