Dexscreener Emojicoin Support
econia-labs/aptos-indexer-processors pull request #67
Opened 2024-12-03 08:39 UTC by CapCap

2024-12-04 16:19 UTC, CRBl69 requested changes
This looks mainly good to me. The only thing is that I do not like the fact that `block_number` and `evnet_index` are options/nullable. I would rather set them as `NOT NULL` and remove the option logic. This would make the processor impossible to upgrade, and we'd have to deploy a new stack. I think this is ok, as the backfilling won't take too much, and we can change the backend that the frontend points to very easily. @alnoki @xbtmatt opinions on this ?

2024-12-04 18:01 UTC, alnoki commented
> I would rather set them as NOT NULL and remove the option logic

@CapCap I agree with @CRBl69 's assessment on this

Backwards compatibility is not necessarily a requirement this early, so is cleanest to simply start a new deployment with breaking logic then have any calling resources point at the new stack once it has backfilled

2024-12-06 00:34 UTC, CapCap commented
@alnoki @CRBl69 if that's the prefered way of doing it, works for me, less pain on my end :-) 

@xbtmatt I guess I won't be doing the backfill BQ stuff then- will just make it mandatory from start

2024-12-06 09:57 UTC, CRBl69 requested changes
The changes look mainly good. Logic is good. Just a couple of very minor changes and then we're good to merge.

2024-12-06 09:57 UTC, CRBl69 commented on rust/processor/src/db/postgres/migrations/2024-12-03-050428_add_block_number_and_event_index/up.sql
> +        ADD COLUMN event_index NUMERIC NOT NULL,
```suggestion
        ADD COLUMN event_index NUMERIC NOT NULL;
```

2024-12-06 09:57 UTC, CRBl69 commented on rust/processor/src/db/postgres/schema.rs
> +
It seems you have manually added this lines.

This file is actually generated by the `diesel` CLI whenever you run migrations for the first time.

I suggest you start a clean DB and run the migrations to update this file (right now, the int types are incorrect).

You can use these commands:

```sh
docker run -d --rm \
  --name econia_db_test \
  -e POSTGRES_PASSWORD=pgpw \
  -e POSTGRES_DB=econia \
  -p 37949:5432 postgres

export DATABASE_URL=postgres://postgres:pgpw@localhost:37949/econia

diesel database setup
```

Note that once the int types will be updated in the `schema.rs`, you'll probably also have to replace some `i64`s with `BigDecimal`s.

2024-12-06 19:49 UTC, CRBl69 approved these changes

2024-12-09 12:45 UTC, merged